name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/gshankarwenli
            git pull origin master
            
            echo "Deploying Frontend..."
            cd frontend
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name "frontend" -- start
            
            echo "Deploying Backend..."
            cd ../backend
            npm install
            pm2 restart backend || pm2 start npm --name "backend" -- start





            